version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: fans_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fans_db
      POSTGRES_USER: fans_user
      POSTGRES_PASSWORD: fans_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fans_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fans_user -d fans_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Python AI Service
  ai-service:
    build: ./backend/ai-service
    container_name: fans_ai_service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - fans_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js Main API
  main-api:
    build: ./backend/api
    container_name: fans_main_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=fans_user
      - DB_PASSWORD=fans_password
      - DB_DATABASE=fans_db
      - AI_SERVICE_URL=http://ai-service:8000
      - NAVER_CLIENT_ID=XqQjKhBGlQbHUwQzaXjX
      - NAVER_CLIENT_SECRET=82CP_wfP9w
      - KAKAO_CLIENT_ID=a931fbb713e76936aa318cec623a33f4
      - KAKAO_CLIENT_SECRET=2VaTsS9v9zbSOBKIfEf3Q6RyCMmlG0ZL
      - KAKAO_REDIRECT_URI=http://localhost:3000/api/auth/kakao/callback
      - NAVER_REDIRECT_URI=http://localhost:3000/api/auth/naver/callback
      - FRONTEND_URL=http://localhost:3001
      - ALLOW_ORIGIN=http://localhost:3001
      - SESSION_SECRET=fans-session-secret-key-2024
      - JWT_SECRET=fans-jwt-secret-key-2024
    depends_on:
      postgres:
        condition: service_healthy
      ai-service:
        condition: service_healthy
    networks:
      - fans_network
    volumes:
      - ./backend/api:/app
      - /app/node_modules

# React Frontend
  frontend:
    build: ./frontend
    container_name: fans_frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_AI_SERVICE_URL=http://localhost:8000
      - PORT=3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fans_network
    depends_on:
      - main-api

volumes:
  postgres_data:

networks:
  fans_network:
    driver: bridge