version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fans_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fans_db
      POSTGRES_USER: fans_user
      POSTGRES_PASSWORD: fans_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fans_user -d fans_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: